const express = require('express')
const app = express()
const port = 9000

var cors = require('cors') 
app.use(cors())

app.use(express.json())
const fs = require('fs')


const multer  = require('multer')

const mystorage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'public/uploads')
  },
  filename: function (req, file, cb) 
  {
    cb(null, Date.now() + file.originalname)
  }
})

const upload = multer({ storage: mystorage })

const mongoose = require('mongoose');

mongoose.connect('mongodb://127.0.0.1:27017/ecomdb')//here ecomdb is the name of your database in the backend
  .then(() => console.log('MongoDB Connected!')).catch((e)=>console.log("Unable to connect to MongoDB " + e.message));

const RegisterSchema = mongoose.Schema({name: String, phone: String, username:{unique:true,type:String}, password:String, usertype:String},{versionKey:false});
//schema defines the structure of the collection/table in database. means the name of columns and its datatype

const RegisterModel = mongoose.model("register",RegisterSchema,"register");//internal collection name, SchemaName, real collection name

app.post("/api/register",async(req,res)=>
{
    try
    {
      const newrecord = RegisterModel({name:req.body.pname,phone:req.body.phone,username:req.body.uname,password:req.body.pass,usertype:"normal"})
      const result = await newrecord.save();//saving document to real collection
      if(result)
      {
        res.send({success:true})
      }
      else
      {
        res.send({success:false})
      }
    }
    catch(e)
    {
      res.send({success:false})
      console.log(e.message)
    }
})

app.post("/api/login",async(req,res)=>
{
    try
    {
      const result = await RegisterModel.findOne({username:req.body.uname,password:req.body.pass}).select("-password")
      if(result===null)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,udata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/searchuser",async(req,res)=>
{
    try
    {
      const result = await RegisterModel.findOne({username:req.query.em})
      if(result===null)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,udata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getallusers",async(req,res)=>
{
    try
    {
      const result = await RegisterModel.find()
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,udata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.delete("/api/deluser/:userid",async(req,res)=>
{
    try
    {
      const result = await RegisterModel.deleteOne({_id:req.params.userid})
      if(result.deletedCount===1)
      {
        res.send({success:1})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.put('/api/changepassword',async(req,res)=>
{
  try
  {
    const result = await RegisterModel.updateOne({username:req.body.uname,password:req.body.cpass},{password:req.body.newpass})
    console.log(result);
    if(result.modifiedCount===1)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

//Category APIs

const CategorySchema = mongoose.Schema({catname:String,picname:String},{versionKey:false});

const CategoryModel = mongoose.model("category",CategorySchema,"category");//internal collection name, SchemaName, real collection name

app.post('/api/savecategory', upload.single('pic'), async(req, res)=>
{
  try
  {
    var imagename="defaultpic.jpeg";
    if(req.file)
    {
      imagename=req.file.filename;
      //fetching the name of file generated by multer. Here filename is the key of multer in disk storage engine
    }
    const newrecord = CategoryModel({catname:req.body.catname,picname:imagename})
    const result = await newrecord.save();//saving document to real collection
    if(result)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

app.get("/api/getallcat",async(req,res)=>
{
    try
    {
      const result = await CategoryModel.find()
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,cdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.put('/api/updatecategory', upload.single('pic'), async(req,res)=>
{
  try
  {
    var imagename;
    if(req.file)
    {
      imagename=req.file.filename;
      if(req.body.oldpicname!=="defaultpic.jpeg")
      {
        fs.unlinkSync(`${req.file.destination}/${req.body.oldpicname}`);
        //public/uploads/14264897998yf447aa975nba.jpeg
      }
      //fetching the name of file generated by multer. Here filename is the key of multer in disk storage engine
    }
    else
    {
        imagename=req.body.oldpicname;
    }
    const result = await CategoryModel.updateOne({_id:req.body.cid},{catname:req.body.catname,picname:imagename})
    if(result.modifiedCount===1)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

app.delete("/api/delcat/:catid",async(req,res)=>
{
    try
    {
      const result = await CategoryModel.deleteOne({_id:req.params.catid})
      if(result.deletedCount===1)
      {
        res.send({success:1})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

//Product API
 
const ProductSchema = mongoose.Schema({catid:String,prodname:String,rate:Number,discount:Number,stock:Number,featured:String,description:String,picname:String,addedon:Date},{versionKey:false});

const ProductModel = mongoose.model("product",ProductSchema,"product");//internal collection name, SchemaName, real collection name

app.post('/api/saveproduct', upload.single('pic'), async(req, res)=>
{
  try
  {
    var imagename="defaultpic.jpeg";
    if(req.file)
    {
      imagename=req.file.filename;
      //fetching the name of file generated by multer. Here filename is the key of multer in disk storage engine
    }
    const newrecord = ProductModel({catid:req.body.cid,prodname:req.body.pname,rate:req.body.rate,discount:req.body.dis,stock:req.body.stock,featured:req.body.feat,description:req.body.description,picname:imagename,addedon:new Date()})

    const result = await newrecord.save();//saving document to real collection
    if(result)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

app.get("/api/getprodsbycat",async(req,res)=>
{
    try
    {
      const result = await ProductModel.find({catid:req.query.cid})
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,pdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.put('/api/updateprod', upload.single('pic'), async(req,res)=>
{
  try
  {
    var imagename;
    if(req.file)
    {
      imagename=req.file.filename;
      if(req.body.oldpicname!=="defaultpic.jpeg")
      {
        fs.unlinkSync(`${req.file.destination}/${req.body.oldpicname}`);
        //public/uploads/14264897998yf447aa975nba.jpeg
      }
      //fetching the name of file generated by multer. Here filename is the key of multer in disk storage engine
    }
    else
    {
        imagename=req.body.oldpicname;
    }
    const result = await ProductModel.updateOne({_id:req.body.pid},{prodname:req.body.pname,rate:req.body.rate,discount:req.body.dis,stock:req.body.stock,featured:req.body.feat,description:req.body.descrip,picname:imagename})
    if(result.modifiedCount===1)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

app.delete("/api/delprod/:pid",async(req,res)=>
{
    try
    {
      const result = await ProductModel.deleteOne({_id:req.params.pid})
      if(result.deletedCount===1)
      {
        res.send({success:1})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getproddetailsbyid",async(req,res)=>
{
    try
    {
      const result = await ProductModel.findOne({_id:req.query.prodid})
      if(result===null)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,pdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/searchproducts",async(req,res)=>
{
    try
    {
      const result = await ProductModel.find({prodname: { $regex: '.*' + req.query.q ,$options:'i' }})
      if(result.length>0)
      {
        res.send({success:1,pdata:result})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getlatestprods",async(req,res)=>
{
    try
    {
      const result = await ProductModel.find().sort({"addedon":-1}).limit(6)
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,pdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getfeaturedprods",async(req,res)=>
{
    try
    {
      const result = await ProductModel.find({"featured":"yes"}).sort({"addedon":-1}).limit(6)
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,pdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})


//Cart APIs

const CartSchema = mongoose.Schema({pid:String,pname:String,rate:Number,qty:Number,totalcost:Number,picname:String,username:String},{versionKey:false});

const CartModel = mongoose.model("cart",CartSchema,"cart");//internal collection name, SchemaName, real collection name

app.post('/api/savetocart', async(req, res)=>
{
  try
  {
    const newrecord = CartModel({pid:req.body.pid,pname:req.body.prodname,rate:req.body.remcost,qty:req.body.qty,totalcost:req.body.tc,picname:req.body.picname,username:req.body.uname})
    const result = await newrecord.save();//saving document to real collection
    if(result)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})

app.get("/api/getcart",async(req,res)=>
{
    try
    {
      const result = await CartModel.find({username:req.query.uname})
      if(result.length===0)
      {
        res.send({success:0})
      }
      else
      {
        res.send({success:1,cdata:result})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.delete("/api/delfromcart/:cartid",async(req,res)=>
{
    try
    {
      const result = await CartModel.deleteOne({_id:req.params.cartid})
      if(result.deletedCount===1)
      {
        res.send({success:1})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

//Order API

const orderSchema = new mongoose.Schema({address:String,pmode:String,carddetails:Object,username:String,billamt:Number,orderitems:[Object],status:String,orderDate:Date},{versionKey:false})

const orderModel = mongoose.model("finalorder",orderSchema,"finalorder")

app.post('/api/saveorder', async(req, res)=>
{
  try
  {
    const items = await CartModel.find({username:req.body.uname})

    const newrecord = orderModel({address:req.body.addr,pmode:req.body.pmode,carddetails:req.body.cardetails,username:req.body.uname,billamt:req.body.billamt,orderitems:items,status:"Order Confirmed",orderDate:new Date()})

    const result = await newrecord.save();//saving document to real collection
    if(result)
    {
        for(var x=0;x<items.length;x++)
        {
          const updateresult = await ProductModel.updateOne({_id:items[x].pid},{$inc:{"stock":-items[x].qty}})
        }
        const delresult = await CartModel.deleteMany({username:req.body.uname})
        res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
    res.send({success:-1})
    console.log(e.message)
  }
})


app.get("/api/getorderdetails",async(req,res)=>
{
    try
    {
      const result = await orderModel.findOne({username:req.query.un}).sort({"orderDate":-1})
      if(result)
      {
        res.send({success:1,odata:result})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getallorders",async(req,res)=>
{
    try
    {
      const result = await orderModel.find().sort({"orderDate":-1})
      if(result.length>0)
      {
        res.send({success:1,odata:result})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/getuserorders",async(req,res)=>
{
    try
    {
      const result = await orderModel.find({username:req.query.uname}).sort({"orderDate":-1})
      if(result.length>0)
      {
        res.send({success:1,odata:result})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.get("/api/fetchorderitems",async(req,res)=>
{
    try
    {
      const result = await orderModel.findOne({_id:req.query.oid})
      if(result)
      {
        res.send({success:1,items:result.orderitems})
      }
      else
      {
        res.send({success:0})
      }
    }
    catch(e)
    {
      res.send({success:-1})
      console.log(e.message)
    }
})

app.put("/api/updatestatus",async(req,res)=>
{
  try
  {
    const result = await orderModel.updateOne({_id:req.body.orderid},{status:req.body.newstatus})
    console.log(result)
    if(result.modifiedCount===1)
    {
      res.send({success:1})
    }
    else
    {
      res.send({success:0})
    }
  }
  catch(e)
  {
   res.send({success:-1})
  }
})

app.listen(port, () => {
  console.log(`Server running on port ${port}`)
})
